import json
from datetime import datetime
import streamlit as st

def export_results_as_json(results, user_input):
    """
    Export the results and user input as a JSON string
    """
    export_data = {
        "user_input": user_input,
        "results": results,
        "exported_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    return json.dumps(export_data, indent=2)

def format_results_as_markdown(results, user_input):
    """
    Format the results as markdown for export or display
    """
    roles = results.get("role_fit", {}).get("recommended_roles", [])
    paths = results.get("career_path", {}).get("career_paths", [])
    skill_gaps = results.get("action_plan", {}).get("skill_gaps", [])
    action_plan = results.get("action_plan", {}).get("action_plan", "")
    
    md = f"""# Career Guidance Report
Generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Your Profile
- **Skills**: {', '.join(user_input.get('skills', []))}
- **Interests**: {', '.join(user_input.get('interests', []))}
- **Experience**: {user_input.get('experience', 0)} years

## Recommended Roles
"""
    
    if roles:
        for role in roles:
            md += f"- {role}\n"
    else:
        md += "No roles found.\n"
    
    md += "\n## Career Paths\n"
    
    if paths:
        for path in paths:
            md += f"- {path}\n"
    else:
        md += "No career paths found.\n"
    
    md += "\n## Skill Gaps\n"
    
    if skill_gaps and any(gap.strip() for gap in skill_gaps):
        for gap in skill_gaps:
            if gap and gap.strip().lower() not in ["none", "undefined"]:
                md += f"- {gap}\n"
    else:
        md += "No significant skill gaps identified.\n"
    
    md += "\n## Action Plan\n"
    
    if action_plan and action_plan.strip() and action_plan.strip().lower() not in ["no action plan generated.", "none", "undefined"]:
        md += action_plan
    else:
        md += "No action plan was generated.\n"
    
    md += "\n\n---\nGenerated by VishCraft Career Guidance"
    
    return md
